backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Journal Entries"
    folder: "_posts/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Cover Image", name: "image", widget: "image"}

  - name: "trips"
    label: "Trips"
    folder: "_posts/trips"
    create: true
    fields:
      - {label: "Trip Name", name: "title", widget: "string"}
      - {label: "Difficulty", name: "difficulty", widget: "select", options: ["Easy", "Moderate", "Hard"]}
      - {label: "Itinerary Details", name: "body", widget: "markdown"}